Depend on version 0.2.0 of the core library, as version 0.1.0 gives a NoSuchMethodError Exception when trying to run Harvest. Also, added an eclipse plugin to the pom due to a known bug in version 2.7 of the maven eclipse plugin.